module.exports = {
  apps: [
    // Frontend is now served by nginx (static dist/ build).
    // This faucet server handles /api/* requests proxied by nginx.
    {
      name: 'value-faucet',
      script: '/home/gorcore/Drift-Clone/frontend/server.mjs',
      cwd: '/home/gorcore/Drift-Clone/frontend',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        PORT: '3001',
        NODE_ENV: 'production',
        RPC_URL: 'https://devnet.helius-rpc.com/?api-key=d251870d-cc90-4544-9a60-f786ebff3966',
      },
    },
    {
      name: 'value-dlob',
      script: '/home/gorcore/Drift-Clone/dlob-server/lib/index.js',
      cwd: '/home/gorcore/Drift-Clone/dlob-server',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        ENDPOINT: 'https://devnet.helius-rpc.com/?api-key=d251870d-cc90-4544-9a60-f786ebff3966',
        WS_ENDPOINT: 'wss://devnet.helius-rpc.com/?api-key=d251870d-cc90-4544-9a60-f786ebff3966',
        ENV: 'devnet',
        DRIFT_PROGRAM_ID: 'EvKyHhYjCgpu335GdKZtfRsfu4VoUyjHn3kF3wgA5eXE',
        PORT: '6969',
        ELASTICACHE_HOST: 'localhost',
        ELASTICACHE_PORT: '6379',
        LOCAL_CACHE: 'true',
        RUNNING_LOCAL: 'true',
        USE_REDIS: 'true',
        REDIS_CLIENT: 'DLOB',
        METRICS_PORT: '9467',
        BULK_ACCOUNT_LOADER_POLLING_INTERVAL: '5000',
        EVENT_SUBSCRIBER_POLLING_INTERVAL: '5000',
        RATE_LIMIT_CALLS_PER_SECOND: '100',
      },
    },
    {
      name: 'value-oracle',
      script: '/home/gorcore/Drift-Clone/scripts/oracle-updater.mjs',
      cwd: '/home/gorcore/Drift-Clone',
      args: '--loop --interval 10000',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
    {
      name: 'value-filler',
      script: '/home/gorcore/Drift-Clone/keeper-bots-v2/lib/index.js',
      cwd: '/home/gorcore/Drift-Clone/keeper-bots-v2',
      args: '--config-file=value-filler.config.yaml',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        KEEPER_PRIVATE_KEY: '/home/gorcore/Drift-Clone/keys/filler-keypair.json',
        DRIFT_PROGRAM_ID: 'EvKyHhYjCgpu335GdKZtfRsfu4VoUyjHn3kF3wgA5eXE',
      },
    },
    {
      name: 'value-liquidator',
      script: '/home/gorcore/Drift-Clone/keeper-bots-v2/lib/index.js',
      cwd: '/home/gorcore/Drift-Clone/keeper-bots-v2',
      args: '--config-file=value-liquidator.config.yaml',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        KEEPER_PRIVATE_KEY: '/home/gorcore/Drift-Clone/keys/liquidator-keypair.json',
        DRIFT_PROGRAM_ID: 'EvKyHhYjCgpu335GdKZtfRsfu4VoUyjHn3kF3wgA5eXE',
      },
    },
    {
      name: 'value-maker',
      script: '/home/gorcore/Drift-Clone/keeper-bots-v2/lib/index.js',
      cwd: '/home/gorcore/Drift-Clone/keeper-bots-v2',
      args: '--config-file=value-maker.config.yaml',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        KEEPER_PRIVATE_KEY: '/home/gorcore/Drift-Clone/keys/maker-keypair.json',
        HEALTH_CHECK_PORT: '8892',
        DRIFT_PROGRAM_ID: 'EvKyHhYjCgpu335GdKZtfRsfu4VoUyjHn3kF3wgA5eXE',
      },
    },
  ],
};
