module.exports = {
  apps: [
    {
      name: 'float-validator',
      script: '/home/gorcore/.local/share/solana/install/active_release/bin/solana-test-validator',
      args: [
        '--ledger', '/home/gorcore/validator-ledger',
        '--bpf-program', 'EvKyHhYjCgpu335GdKZtfRsfu4VoUyjHn3kF3wgA5eXE',
          '/home/gorcore/Drift-Clone/protocol-v2/target/deploy/drift.so',
        '--account', 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
          '/home/gorcore/Drift-Clone/protocol-v2/deps/configs/usdc.json',
        '--account', '3rdJbqfnagQ4yx9HXJViD4zc4xpiSqmFsKpPuSCQVyQL',
          '/home/gorcore/Drift-Clone/protocol-v2/deps/configs/pyth_lazer_storage.json',
        '--bind-address', '0.0.0.0',
        '--rpc-port', '8899',
        '--quiet',
      ].join(' '),
      interpreter: 'none',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
      env: {
        PATH: '/home/gorcore/.local/share/solana/install/active_release/bin:/home/gorcore/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
      },
    },
    {
      name: 'float-frontend',
      script: 'npx',
      args: 'vite --host 0.0.0.0 --port 5173',
      cwd: '/home/gorcore/Drift-Clone/frontend',
      interpreter: 'none',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        PATH: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        NODE_ENV: 'production',
      },
    },
    {
      name: 'float-dlob',
      script: '/home/gorcore/Drift-Clone/dlob-server/lib/index.js',
      cwd: '/home/gorcore/Drift-Clone/dlob-server',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 3000,
      env: {
        ENDPOINT: 'http://127.0.0.1:8899',
        WS_ENDPOINT: 'ws://127.0.0.1:8900',
        ENV: 'devnet',
        DRIFT_PROGRAM_ID: 'EvKyHhYjCgpu335GdKZtfRsfu4VoUyjHn3kF3wgA5eXE',
        PORT: '6969',
        ELASTICACHE_HOST: 'localhost',
        ELASTICACHE_PORT: '6379',
        LOCAL_CACHE: 'true',
        RUNNING_LOCAL: 'true',
        USE_REDIS: 'true',
        REDIS_CLIENT: 'DLOB',
        METRICS_PORT: '9467',
        BULK_ACCOUNT_LOADER_POLLING_INTERVAL: '5000',
        EVENT_SUBSCRIBER_POLLING_INTERVAL: '5000',
        RATE_LIMIT_CALLS_PER_SECOND: '100',
      },
    },
    {
      name: 'float-oracle',
      script: '/home/gorcore/Drift-Clone/scripts/oracle-updater.mjs',
      cwd: '/home/gorcore/Drift-Clone',
      args: '--loop --interval 10000',
      autorestart: true,
      max_restarts: 10,
      restart_delay: 5000,
    },
  ],
};
